
CFLAGS := -fPIC -O3 -Wall
CXXFLAGS := $(CFLAGS)

PLUGIN_LDFLAGS := -shared -Wl,-Bstatic -L../vamp-plugin-sdk -lvamp-sdk -Wl,-Bdynamic -lpthread -Wl,--version-script=vamp-plugin.map

PLUGIN_EXT := .so

include Makefile.inc
